baseURL = "https://stomper10.github.io/"
languageCode = "en-us"
title = "My Hugo Blog"
theme = "ananke"
publishDir = "public"

[outputs]
home = ["HTML", "RSS"]
section = ["HTML", "RSS"]
taxonomy = ["HTML", "RSS"]
