baseURL = "https://stomper10.github.io/"
languageCode = "en-us"
title = "Stomper"
theme = "ananke"
publishDir = "public"
contentDir = "content"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = true

[languages]
  [languages.en]
    title = "Stomper's Blog"
    weight = 1
    languageName = "English"
    contentDir = "content/en"

  [languages.ko]
    title = "Stomper 블로그"
    weight = 2
    languageName = "한국어"
    contentDir = "content/ko"

[outputs]
home = ["HTML", "RSS"]
page = ["HTML"]
section = ["HTML", "RSS"]
taxonomy = ["HTML", "RSS"]

[permalinks]
  posts = "/posts/:slug/"

[taxonomies]
  category = "categories"
  tag = "tags"

[params]
  custom_css = ["css/custom.css"]
  disqus_developer = true
  background_image = "images/cover.jpg"

[services.disqus]
  shortname = 'stomper10'